.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SHOGUN 5 "August  1, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
shogun \-  A Large Scale Machine Learning Toolbox
.SH SYNOPSIS
.B shogun
.RI [ options ]
.br
.SH DESCRIPTION
This manual page briefly documents the readline interface of
.B shogun
.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBShogun\fP is a large scale machine learning toolbox with focus on large
scale kernel methods and especially on Support Vector Machines (SVM) with focus
to bioinformatics. It provides a generic SVM object interfacing to several
different SVM implementations. Each of the SVMs can be combined with a variety
of the many kernels implemented. It can deal with weighted linear combination
of a number of sub-kernels, each of which not necessarily working on the same
domain, where  an optimal sub-kernel weighting can be learned using Multiple
Kernel Learning.  Apart from SVM 2-class classification and regression
problems, a number of linear methods like Linear Discriminant Analysis (LDA),
Linear Programming Machine (LPM), (Kernel) Perceptrons and also algorithms
to train hidden markov models are implemented. The input feature-objects
can be dense, sparse or strings and of type int/short/double/char and can
be converted into different feature types. Chains of preprocessors (e.g.
substracting the mean) can be attached to each feature object
allowing for on-the-fly pre-processing.

.SH OPTIONS
A summary of options is included below.
.TP
.B \-h, \-\-help, /?
Show summary of options.
.TP
.B \-i
listen on tcp port 7367 (hex of sg)
.TP
.B filename
execute a script by reading commands from file <filename>
.TP
when no options are given the interactive readline interface will be entered
.TP
.SH SEE ALSO
.BR svm-train (1),
.BR svm-predict (1).
.BR svm-scale (1).
.TP
.SH AUTHOR
.br
shogun was written by Soeren Sonnenburg <Soeren.Sonnenburg@first.fraunhofer.de>
and Gunnar Raetsch <Gunnar.Raetsch@tuebingen.mpg.de>
.PP
This manual page was written by Soeren Sonnenburg <sonne@debian.org>,
for the Debian project (but may be used by others).
